### ISSUE TITLE
XXButtons as Hotclicks not working since 1.55

### ISSUE THREAD

**Issue by askii2** [RamonUnch/AltSnap#433] opened 2023-05-29 02:24 UTC
Using extra mouse buttons as triggers is not working since 1.55 for me, it works fine on 1.53 an 1.54.
I mapped mouse button 6 to F13 and put ```Hotclicks=07``` and ```XXButtons=7C``` in my AltSnap.ini.

If i revert this change: https://github.com/RamonUnch/AltSnap/blame/71f587b259c8636d5914a868f4ad4475d5078b81/hooks.c#L2557-L2558, i.e:
```C
        } else if ((xxbtidx = XXButtonIndex(vkey)) >=0
        && (GetAction(BT_MMB+xxbtidx) ||  GetActionT(BT_MMB+xxbtidx))) /* NEW */
```
to
```C
        } else if ((xxbtidx = XXButtonIndex(vkey)) >=0 ) { /* OLD */
```
they start working again, but i don't know the possible side-effect and i imagine it was changed to fix another issue.

**Comment by RamonUnch** [comment] 2023-05-29 06:41
Indeed I forgot about the hotclick scenario, I wanted to avoid interaction if no action was mapped. I will add a Hotclick check Or I could remove again this check (as you did) because if you no longer want to use an XX buttons, users might as well remove it from the list.
Thanks a lot for reporting, This will be fixed for next release.

**Comment by RamonUnch** [comment] 2023-05-29 06:46
However it is a little strange, while still perfectly valid, to remap F13 to mouse button 7 to then use the button as a hotclick when F13 can directly be used as a hotkey, in this case pressing the physical mouse button will activate AltSanp. Maybe there is a reason you are using an extra indirection?

**Comment by RamonUnch** [comment] 2023-05-29 07:07
Fix with added condition to check for a hotclick:

[AltSnap1.61test10_x64.zip](https://github.com/RamonUnch/AltSnap/files/11589337/AltSnap1.61test10_x64.zip)
[AltSnap1.61test10_i386.zip](https://github.com/RamonUnch/AltSnap/files/11589352/AltSnap1.61test10_i386.zip)

It is a significant enough regression to deserves a dedicated release so I will probably wait a little and make a new release.

**Comment by askii2** [comment] 2023-05-29 18:05
Thank you very much. It is working normally now.

**Closed** 2023-06-05 07:20 UTC
Labels: bug, good first issue
