### ISSUE TITLE
Autostart creates instance in task manager that doesn't work

### ISSUE THREAD

**Issue by logarythmic** [RamonUnch/AltSnap#52] opened 2021-05-03 17:15 UTC
I've tried uninstalling and messing around with my startup app settings and task scheduler in order to get this fixed without any luck. When it's started in either two of those ways it will run as a Background process with 1 MB of memory but not work at all. Only when I manually click on does it launch a new instance that takes up 2.5 - 4MB of memory does it work.

Any help would be much appreciated.

**Comment by RamonUnch** [comment] 2021-05-03 17:47
Try to add a 10s delay in the task scheduler.
Have a look to https://github.com/RamonUnch/AltDrag/issues/15 and https://github.com/stefansundin/altdrag/issues/77

**Comment by logarythmic** [comment] 2021-05-03 18:04
I saw that and gave it a try, but that also led to an instance of 1.3 MB instance that did not work. There was also a bat file I tried to run that killed any running instances before launching it again after a delay.

**Comment by RamonUnch** [comment] 2021-05-03 18:12
Strange, so you mean that when you lunch AltDrag from the autostart it does not work.
Does it work at least when you lunch it by doubleclick after a clean restart?
I think this old bat served to kill a AltDrag when it was stuck in an infinite loop that has been fixed a while back now.

I have no idea what could cause the problem then.
Just in case give me your ini file (you can zip it and attach it in a post).
Which version of windows are you using?
I guess you are trying to lunch AltDrag as admin?

**Comment by RamonUnch** [comment] 2021-05-03 18:13
Does the same thing happen with the original AltDrag?

**Comment by logarythmic** [comment] 2021-05-03 18:19
Anytime I manually launch or double click it works perfectly. I actually switched to your version in the hopes of fixing this. It only happened in the past week while trying to task schedule my way out of the annoying UAC prompt. Everything but autostart works perfectly, it's really weird.

([AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6416837/AltDrag.zip))


Currently on OS build: 19042.928 of Windows 10

**Comment by RamonUnch** [comment] 2021-05-03 18:25
Ok, I will try to get a deeper look into this.
I guess I will make a version that logs out all the possible information.

You mean that the "normal" autostart (that can be checked in the config dialog) does not work either?
The only problem is when using the task scheduler?

It is true that I did not test much using the task scheduler. As I said I will investigate more because there seems to be some reproducible problems around here...

**Comment by logarythmic** [comment] 2021-05-03 18:31
Awesome thank you! I'm really curious to see what the issue is. I've been experimenting with having autostart on and off in tandem with task scheduler with no success. I'll let you know if I can think of anything else that might lead you in the right direction.

**Comment by RamonUnch** [comment] 2021-05-03 19:34
Try with this combo AltDrag.exe+Hooks.dll:
[AltDrag_log.zip](https://github.com/RamonUnch/AltDrag/files/6417221/AltDrag_log.zip)

rename the old altdrag.exe+Hooks.dll in something different and copy the new ones.
AltDrag should create a ad.log in its dirrectorry when lunched, thus:
Try to lunch AltDrag by double-click, in this case everything *should* work fine.
then exit AltDrag, 
then rename the ad.log in ad-normal.log, you ca give it a read if you like.
Then keep AltDrag off, set up the autostart in your tasks, restart and rename the new ad.log in ad-sched.log, then send me both logs and we will see.

**Comment by logarythmic** [comment] 2021-05-03 19:49
I think I did this right, take a look and let me know if that's what you were looking for. It did the thing it usually does, so I hope it was accurately captured.

[Logs.zip](https://github.com/RamonUnch/AltDrag/files/6417290/Logs.zip)

**Comment by RamonUnch** [comment] 2021-05-03 20:40
Could you try again a restart with the scheduled task?
The log should logically always start with ALTDRAG STARTED WITH HINSTANCE 0x... something.
Even if AltDrag does not work I except this message because it is the first one. It seems the ad-sched.log you gave me was taken in the midle of the execution.
So just leave ad.log alone, and restart with the scheduled task again, Quit AltDrag and send me again the new ad.log.

**Comment by logarythmic** [comment] 2021-05-03 20:55
I think I just figured it out after googling a bit about the task scheduler. I changed it from to "Run weather user is logged on or not" to "Run only when user is logged on" which fixed it at least for this current restart. No idea why the autostart within the app itself wasn't working, but at least there is a workaround for the moment.

Here is ad for when I exited out and manually ran the task:
[ad-nousertsched.log](https://github.com/RamonUnch/AltDrag/files/6417659/ad-nousertsched.log)

**Comment by RamonUnch** [comment] 2021-05-03 21:11
> "Run only when user is logged on"
This is actually expected, AltDrag can not do anything for the current user if he is not logged on.
AltDrag is not like a driver and only hooks the keyboard and mouse of the current user, this mean that there are no interactions with other users even if you use elevated mode.
AltDrag also needs for the proper display of the tray icon that the taskbar is lunched. 
I guess This is why it was not working. I thought that this option was the default and I did not think about it, but it make sense.

Anyway your probles *should* be fixed. It should not be possible for AltDrag to work if the option is "Run weather user is logged on or not" and there is no possible way to make it work like this.
However the "normal" autostart should be fixed still.
I will add to the txt file the details on how to prepare this scheduled task

**Comment by logarythmic** [comment] 2021-05-03 22:15
Ah okay, that's really good to know! Thanks so much for the help, I really appreciate it.

**Comment by RamonUnch** [comment] 2021-05-04 09:46
[First response](https://github.com/RamonUnch/AltDrag/issues/52#issuecomment-831421795) was updated with details to help setting Autostart

**Closed** 2021-09-13 13:38 UTC
Labels: bug
