### ISSUE TITLE
Extend/Snap to next edge

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#368] opened 2023-02-16 12:59 UTC
To fill the niche between `Extend to Side/Corner` and `Snap to Side/Corner`.

To visualize the `Extend to next Edge` action:
![1](https://user-images.githubusercontent.com/31080003/219371272-cdccc553-8969-4d73-b3d1-f29f25a45823.png)
![2](https://user-images.githubusercontent.com/31080003/219371286-a7be9d74-17b0-435c-bc5d-ab619f0cde43.png)

**Comment by RamonUnch** [comment] 2023-02-16 13:59
Interesting, do you think it should consider all windows borders or just borders of snapped windows.

**Comment by Ichisich** [comment] 2023-02-16 14:04
The aero snap setting could be the defining factor (Mimic/Smart/Smarter). 
This would guaranty a more consistent behavior for most user.

**Comment by RamonUnch** [comment] 2023-02-18 13:56
This one should do the trick.

[AltSnap1.59test17_i386.zip](https://github.com/RamonUnch/AltSnap/files/10774392/AltSnap1.59test17_i386.zip)
[AltSnap1.59test17_x64.zip](https://github.com/RamonUnch/AltSnap/files/10774401/AltSnap1.59test17_x64.zip)

You have the new action! `ExtendTNEdge` also available in the drop down actions list in the config dialog.

**Comment by Ichisich** [comment] 2023-02-18 14:30
I set `Extend to next edge` as a while resize action, which sometimes lead the window to get rolled up in the top left corner.
It seems the resize command doesn't get cancelled after the while action, but AltSnap doesn't know exactly what to do with the window.
https://user-images.githubusercontent.com/31080003/219871110-894fc00c-da51-4ca6-a57a-8115bf3269d1.mp4


Setting `Extend to next edge` to a dedicated primary button doesn't show this behavior.

**Comment by RamonUnch** [comment] 2023-02-18 14:36
I forgot to update the action flag
[AltSnap1.59test18_x64.zip](https://github.com/RamonUnch/AltSnap/files/10774501/AltSnap1.59test18_x64.zip)

**Comment by Ichisich** [comment] 2023-02-18 14:44
The roll behaviour is fixed, but now the context menu gets activated (my resize button is RMB).

**Comment by RamonUnch** [comment] 2023-02-18 18:50
Should be fixed.
[AltSnap1.59test19_x64.zip](https://github.com/RamonUnch/AltSnap/files/10774956/AltSnap1.59test19_x64.zip)

**Comment by Ichisich** [comment] 2023-02-18 19:43
It is.

**Comment by zhichaoh** [comment] 2023-02-20 04:27
Great addtion! Can we make the ExtendTNEdge available to keyboard and command line option?

**Comment by RamonUnch** [comment] 2023-02-20 09:15
> Great addtion! Can we make the ExtendTNEdge available to keyboard and command line option?

For now you can use `-apExtendTNEdge` but it depends on cursor position. 4 new actions will have to be made in order to do this for left/right top/bottom.

**Comment by RamonUnch** [comment] 2023-02-20 10:38
With this one you have:
XTNLEdge ("Extend to the next left edge"),
XTNTEdge ("Extend to the next top edge"),
XTNREdge ("Extend to the next right edge"),
XTNBEdge ("Extend to the next bottom edge"),

They can be selected from the config dialog and they can be sed from the command line like `AltSnap.exe -afXTNLEdge`

[AltSnap1.59test20_x64.zip](https://github.com/RamonUnch/AltSnap/files/10783440/AltSnap1.59test20_x64.zip)
[AltSnap1.59test20_i386.zip](https://github.com/RamonUnch/AltSnap/files/10783474/AltSnap1.59test20_i386.zip)

**Comment by RamonUnch** [comment] 2023-02-20 10:40
Note that in general all actions can be used from the command line but they are generally not extensively tested and might be untested.

**Comment by zhichaoh** [comment] 2023-02-20 15:54
@RamonUnch, thank you for the quick implementation. The action works reliably from both keyboard and command line execution. I noticed not all actions are supported in command line. And some of them do not make sense to invoke from command line, (e.g. transparency) as they are more suited for scrolling. But using these actions (Snap, Extend, and Extent to Next Edge) combined with some ahk or mouse gestures, I am able to mimic some of the tiling window managers. Thank you so much!

**Comment by RamonUnch** [comment] 2023-02-20 16:03
Nice to hear that, If you have time, you could consider starting a discussion (in the discussion thread) on how to setup AltSnap+AHK to mimic a tiling window manager, I am sure some people would be interested in that.

I have thought several times working on a tiling mode with Windows but it is not yet in the order of things. Plus I am unfamiliar with tiling windows managers in general, I have played a little with one of them but not enough to be comfortable with them.

**Comment by Ichisich** [comment] 2023-02-20 16:47
The keyboard shortcuts work great

To come back to the `Snap to next edge` part:
![1](https://user-images.githubusercontent.com/31080003/220162682-7fbfd462-cd6d-47bd-99be-ac0efe4e39f0.png)
![2](https://user-images.githubusercontent.com/31080003/220162697-8f48d65b-618f-4ae7-912b-a714214d1eb4.png)

This could also be the shift function of `Extend to next edge`.

**Comment by RamonUnch** [comment] 2023-02-20 17:35
So Snap to next edge would actually just move the window? Is this what you are suggesting?
Could be both a separate action and available with Shift.

**Comment by Ichisich** [comment] 2023-02-20 17:43
>So Snap to next edge would actually just move the window?

Yes.

>Could be both a separate action and available with Shift.

I see the relation between `Extend to next edge` and `Snap to next edge` similar to `Extend to Side/Corner` and `Snap to Side/Corner`.
So the handling convention would dictate both.

**Comment by zhichaoh** [comment] 2023-02-20 17:56
One issue found with [AltSnap1.59test20_x64.zip] is that custom theme no longer gets loaded. @RamonUnch , can you please confirm?

I have this in my ini, btw,
Theme=erasmion

**Comment by RamonUnch** [comment] 2023-02-20 19:29
> One issue found with [AltSnap1.59test20_x64.zip] is that custom theme no longer gets loaded. @RamonUnch , can you please confirm?

I do confirm, it is a typo I made while refactoring.
[AltSnap1.59test21_x64.zip](https://github.com/RamonUnch/AltSnap/files/10787327/AltSnap1.59test21_x64.zip)

**Comment by zhichaoh** [comment] 2023-02-20 19:35
> Nice to hear that, If you have time, you could consider starting a discussion (in the discussion thread) on how to setup AltSnap+AHK to mimic a tiling window manager, I am sure some people would be interested in that.
> 
> I have thought several times working on a tiling mode with Windows but it is not yet in the order of things. Plus I am unfamiliar with tiling windows managers in general, I have played a little with one of them but not enough to be comfortable with them.

Will definitely write up for this.

**Comment by zhichaoh** [comment] 2023-02-20 19:42
@RamonUnch , I found Chrome like browsers or electron apps has troubles when moving the rightmost zone. The right side of the window are cut off (min, max, close buttons) or shift over the right edge so they are invisible. See the screenshot. This problem does not happen with normal desktop apps such as notepad, explorer window etc. Can this issue be addressed in the AltSnap?
![screenshot_20230220_133949_001](https://user-images.githubusercontent.com/3767709/220187170-caa9cb08-421d-4c94-9b5c-c3cd823ec5ed.png)

**Comment by zhichaoh** [comment] 2023-02-21 01:59
I found the root cause of this issue is that Chrome and its derived apps has minimal size and cannot shrink below that size. See: https://stackoverflow.com/questions/59199833/chrome-doesnt-scale-below-x-500px. FancyZone has the same issue. So this not an issue with AltSnap but rather the design of Chrome.

**Comment by RamonUnch** [comment] 2023-02-21 21:27
This one adds the Move To Next edge option. Also accessible via shift on Extend to next edge and vice-versa.
Also keyboard versions were added, this was quite straightforward, I Think I will work on testing for 1.59 release and stop features now.

[hooks1.59test23_x64.zip](https://github.com/RamonUnch/AltSnap/files/10797881/hooks1.59test23_x64.zip)

**Comment by zhichaoh** [comment] 2023-02-22 17:14
> 

The test23 versions works well for me. Having the shift key behaves like the rest of actions makes lots of sense.

**Comment by RamonUnch** [comment] 2023-03-11 08:02
1.59 Released

**Closed by RamonUnch** 2023-03-11 08:02 UTC
Labels: enhancement
