### ISSUE TITLE
These two functions are not working--

### ISSUE THREAD

**Issue by PhoenixCODE2322** [RamonUnch/AltSnap#248] opened 2022-08-02 17:15 UTC
1. Action without click . what i do -- 
a) Press Alt + Ctrl(Modkey) but nothing happens
![image](https://user-images.githubusercontent.com/75798544/182433336-ecc4db2d-cd7b-4ed7-912c-590f777b9922.png)

2)RMBTB=SideSnap :: only this SideSnap is not working other actions seems to work.
here is my config in context of this part 2 function. [Config](https://pastebin.com/QZCcZbz0)

More details :: AltSnap1.54 Portable

**Comment by RamonUnch** [comment] 2022-08-02 19:44
You need to have a primary action assigned in order to have the secondary working.
It is a limitation that was intentional for some reason but it seems it would be better to remove it.

**Comment by RamonUnch** [comment] 2022-08-02 20:02
> 2)RMBTB=SideSnap :: only this SideSnap is not working other actions seems to work.

Side snaps is the equivalent of double-rightclick so it perform a different action on each window quadrant.
It will not behave nicely as a titlebar action. and should only allow you to snap to the top and its corners.

**Comment by PhoenixCODE2322** [comment] 2022-08-03 03:58
> You need to have a primary action assigned in order to have the secondary working. It is a limitation that was intentional for some reason but it seems it would be better to remove it.

yuup that would be good , even though i can't find a good reason to use this. will read the wiki. i remeber there was something mentioned about this.

**Comment by RamonUnch** [comment] 2022-08-03 19:46
This version of hooks.dll should fix the non primary action not working problem.

[hooks1.55test2_i386.zip](https://github.com/RamonUnch/AltSnap/files/9254523/hooks1.55test2_i386.zip)
[hooks1.55test2_x64.zip](https://github.com/RamonUnch/AltSnap/files/9254525/hooks1.55test2_x64.zip)

**Comment by PhoenixCODE2322** [comment] 2022-08-04 03:53
> This version of hooks.dll should fix the non primary action not working problem.
> 
> [hooks1.55test2_i386.zip](https://github.com/RamonUnch/AltSnap/files/9254523/hooks1.55test2_i386.zip) [hooks1.55test2_x64.zip](https://github.com/RamonUnch/AltSnap/files/9254525/hooks1.55test2_x64.zip)

ok tested it , first i got confused like it was not working. was there some misunderstanding ..

so this is happening .. you have to simultaneously press Alt & Win(Mod key) for this to work ... if Alt was presses even 50 ms late this won't work... they need to activate at same time.. this needs fix .. also one more fix that i would like to suggest.

As you can see my first Mod key is Alt and my second Mod key is Win.. now if perform some action and then when i go on releasing the keys in this order then some problem occurs.

1) First Win is released and then Alt is released . -- No problem 
2) First Alt is released and then Win is released . --- Start Menu shows up.
3) both key released at same time -- No problem.

The 2nd one needs a fix , i think. 

Also i can't use Ctrl and Shift as second Mod key because Many function 2nd behaviour depends on this i am left with only win key.
i don't think anything can be done in this respect.

**Comment by RamonUnch** [comment] 2022-08-04 06:27
>so this is happening .. you have to simultaneously press Alt & Win(Mod key) for this to work ... if Alt was presses even 50 ms late this won't work... they need to activate at same time.. this needs fix .. also one more fix that i would like to suggest.

This is normal, you mush have the Mod key down before you start the action with the hotkey. This is because he action starts as soon as the hotkey is down. This is actually very useful for some setup, as Win+Alt can be different than Alt+Win etc.

> As you can see my first Mod key is Alt and my second Mod key is Win.. now if perform some action and then when i go on releasing the keys in this order then some problem occurs.

>    First Win is released and then Alt is released . -- No problem
    First Alt is released and then Win is released . --- Start Menu shows up.
    both key released at same time -- No problem.

I cannot reproduce, unless AltSnap is disabled.

**Comment by RamonUnch** [comment] 2022-08-04 07:27
Ok, I see you meant that Alt and Win were hotkeys right? not ModKeys,
I think I got the problem, it occurs when you press multiple hotkeys at once. and depends on the release order. This one should fix it.

[hooks1.55test3_i386.zip](https://github.com/RamonUnch/AltSnap/files/9257551/hooks1.55test3_i386.zip)
[hooks1.55test3_x64.zip](https://github.com/RamonUnch/AltSnap/files/9257553/hooks1.55test3_x64.zip)

**Comment by PhoenixCODE2322** [comment] 2022-08-04 08:47
> This is normal, you mush have the Mod key down before you start the action with the hotkey. This is because he action starts as soon as the hotkey is down. This is actually very useful for some setup, as Win+Alt can be different than Alt+Win etc.

ok now it make sense. i understand


> Ok, I see you meant that Alt and Win were hotkeys right? not ModKeys, I think I got the problem, it occurs when you press multiple hotkeys at once. and depends on the release order. This one should fix it.


sorry i think , i am just confused by what mod and hotkey is anymore .. i will post my setting screenshot and steps to reproduce the error and also let me know what key is hotkey and Mod key in context of Altsnap.
![image](https://user-images.githubusercontent.com/75798544/182803188-d07a680d-e5bb-4fb3-8e5a-c365f14b4578.png)![image](https://user-images.githubusercontent.com/75798544/182803221-f8b83012-daaf-46e0-b8f3-4b2f09ed6ae8.png)![image](https://user-images.githubusercontent.com/75798544/182803533-e7568921-a9f4-4f0b-89a9-35a98adcfdac.png)

Now steps to reproduce the error (where starts menu pops up if i release Win key later than Alt Key) ---
1. Go to Mouse Tab > Mouse Action > Alternate > Left Mouse Button > Set it to minimize window.
2. Apply Changes and Close Alt Snap Configuration window.
3. Press Alt key and hold > then press Win key and hold > Then press Left mouse button on a window. ( this will result in that window getting minimized)
4. Now first release Alt key > then release Win key
5. Start menu pops up.

this behaviour does not execute when WinKey>AltKey>release AltKey> release WinKey  is done .. 

What are your thoughts , is it good or bad .

**Comment by PhoenixCODE2322** [comment] 2022-08-04 08:49
> Ok, I see you meant that Alt and Win were hotkeys right? not ModKeys, I think I got the problem, it occurs when you press multiple hotkeys at once. and depends on the release order. This one should fix it.
> 
> [hooks1.55test3_i386.zip](https://github.com/RamonUnch/AltSnap/files/9257551/hooks1.55test3_i386.zip) [hooks1.55test3_x64.zip](https://github.com/RamonUnch/AltSnap/files/9257553/hooks1.55test3_x64.zip)

i think this one fixes a bug or not .. i was telling something else ( incomplete . sorry) and you fixed something else . lol

**Comment by RamonUnch** [comment] 2022-08-04 09:23
Ok, now I can reproduce the bug, I will see how to fix it.
The ModKey is the key with which you enable the alternate action (Winkey in your case).
The Hotkey is the key with which you enable AltSnap (Alt in your case).

You can actually use the same key for a Hotkey and a ModKey, so for exaple if add the Winkey to the hotkeys (by checking the  **Left Winkey** box in the the Keyboard tab), tnen Alt+click will perform the primary action and Win+click will perform the alternate action. Of course this is just an example.
It is a bit obscure jargon, that I am using because it is how I named it in the source.

**Comment by PhoenixCODE2322** [comment] 2022-08-04 09:46
> 
> You can actually use the same key for a Hotkey and a ModKey, so for exaple if add the Winkey to the hotkeys (by checking the **Left Winkey** box in the the Keyboard tab), tnen Alt+click will perform the primary action and Win+click will perform the alternate action. Of course this is just an example. It is a bit obscure jargon, that I am using because it is how I named it in the source.

wth , it can be done like this... i alwas thought that win key had to be pressed with Alt key thats why it is called modefier key . lmao
if it can be used to trigger action seprately .. then i don't know - why was i using it in a combo and making my life harder.. bruhhh

**Comment by RamonUnch** [comment] 2022-08-04 09:56
Still it should be fixed, This one better prevents menu activation when releasing the keys after an action.

[hooks1.55test4_i386.zip](https://github.com/RamonUnch/AltSnap/files/9258622/hooks1.55test4_i386.zip)
[hooks1.55test4_x64.zip](https://github.com/RamonUnch/AltSnap/files/9258624/hooks1.55test4_x64.zip)

**Comment by RamonUnch** [comment] 2022-08-04 10:00
>wth , it can be done like this... i always thought that win key had to be pressed with Alt key thats why it is called modefier key . lmao
if it can be used to trigger action seprately .. then i don't know - why was i using it in a combo and making my life harder.. bruhhh

On the older AltDrag it was advised to use two AltDrag instances to perform this, I created this option to avoid having to do this. It is still possible if needed to launch two AltSnap instances.

Everyone have quite different expectations, some users like having to press a combination of keys to enable AltSnap and others have a keyboard-free setup.

**Comment by PhoenixCODE2322** [comment] 2022-08-04 10:11
> Still it should be fixed, This one better prevents menu activation when releasing the keys after an action.
> 
> [hooks1.55test4_i386.zip](https://github.com/RamonUnch/AltSnap/files/9258622/hooks1.55test4_i386.zip) [hooks1.55test4_x64.zip](https://github.com/RamonUnch/AltSnap/files/9258624/hooks1.55test4_x64.zip)

this works perfect .. now i don't have to be consious about which key to release first. Thanks.

**Comment by PhoenixCODE2322** [comment] 2022-08-04 10:14
> > wth , it can be done like this... i always thought that win key had to be pressed with Alt key thats why it is called modefier key . lmao
> > if it can be used to trigger action seprately .. then i don't know - why was i using it in a combo and making my life harder.. bruhhh
> 
> On the older AltDrag it was advised to use two AltDrag instances to perform this, I created this option to avoid having to do this. It is still possible if needed to launch two AltSnap instances.
> 
> Everyone have quite different expectations, some users like having to press a combination of keys to enable AltSnap and others have a keyboard-free setup.

yes . even i was thinking of asking you to implement this kind of behaviour where in future if i get a mouse with extra button .. i can have complete different setup for mouse+extraMouseKeys and keyboard+touchpad to have independent setup.

**Comment by PhoenixCODE2322** [comment] 2022-08-04 10:16
should i close the issue .. i am confuse .. should the dev close the issue or the user ..

**Comment by RamonUnch** [comment] 2022-08-04 10:21
> yes . even i was thinking of asking you to implement this kind of behaviour where in future if i get a mouse with extra button .. i can have complete different setup for mouse+extraMouseKeys and keyboard+touchpad to have independent setup.

Maybe for this one an other AltSnap instance would do the trick.
The support for more than 5 mouse buttons was recently added to AltSnap and is a bit hard to configure. In theory however you can have up to 20 buttons.

**Comment by RamonUnch** [comment] 2022-08-04 10:26
> should i close the issue .. i am confuse .. should the dev close the issue or the user ..

It is not very important, I like to close it with the associated pull request.

**Closed** 2022-08-04 10:31 UTC
Labels: bug
