### ISSUE TITLE
(fancyzones) Snap to Layout with Shift - Ugly screen tearing 

### ISSUE THREAD

**Issue by onguarde** [RamonUnch/AltSnap#218] opened 2022-07-21 07:47 UTC
When "Snap to Layout with Shift" option is enabled, moving windows with alt+shift+drag results in a lot of tearing. The window size keeps changing frantically as you move the mouse. 

I experimented with the Performance parameters in AltSnap.ini file. When RezTimer is set to 0, it gives the best visual experience. When the window size is totally fixed while moving, and eventually it gets resized only once, when you reach a snap layout position. 

I believe this should be the default and documented somewhere in the wiki. 

> RezTimer=1
> ;RezTimer=0 ; orig
> ; Set to 1 to move the window only when the timestamp of
> ; a mouse event is different from the previous one, every 16ms
> ; more or less. MoveRate and ResizeRate and RefreshRate
> ; will have no effect if the option is enabled.
> ; This is overall the option that gives the best performances.
> ; It can be combined with FullWin=0 mode for ~0% CPU usage.

**Comment by onguarde** [comment] 2022-07-21 08:10
I'm using 1000 Hz gaming mouse.

https://user-images.githubusercontent.com/681355/180163747-e4cd51c7-15db-42e0-8027-89da00af83c3.mp4

**Comment by Ichisich** [comment] 2022-07-21 08:13
Try setting `InterZone=0`

**Comment by RamonUnch** [comment] 2022-07-21 09:51
> Try setting `InterZone=0`

I confirm this idea. You are seeing flicker because when you point your mouse between two zones, the window will be resized to cover both. If you set InterZone to zero, then the behaviour will be disabled and the only way to extend a window to several zones will be using Ctrl key.

**Comment by RamonUnch** [comment] 2022-07-21 09:58
However in general I would recommend setting RezTimer=1 if you use a 60Hz monitor.

**Comment by onguarde** [comment] 2022-07-22 03:40
I applied InterZone=0, I can't tell the difference.
RezTimer=1 seems to help a lot, but it's still happening when the windows being moved are complex. Eg. webpages. 

https://user-images.githubusercontent.com/681355/180356313-0ec7699d-fe1a-4ffe-8a97-70e8d08e220c.mp4

I really like the Microsoft FancyZones's implementation,

https://user-images.githubusercontent.com/681355/180356636-d576fda0-9720-46f9-ae28-388e8330622d.mp4

The window is NOT resized at all until it's dropped to the other zone. We can achieve something similar simply by enabling FullWin=0 now. But this setting will also affect normal dragging, without  "snap to layout".

**Comment by Ichisich** [comment] 2022-07-22 07:02
Could you share your AltSnap.ini?

**Comment by RamonUnch** [comment] 2022-07-22 08:02
I agree Fancy zones method is quite good. In general I plan to implement a snapping preview in the future for all kind of snapping see Issue #106 for more.

However the latest test build should fix a part of the problem, because when you start moving a Snapped window it will no longer restore it if you are in Zone-snapping mode. This would cause a visible flicker that could be quite long for windows that are slow drawers.

I would like to see your .ini file, because I do not see how the RezTimer should affect Zone snapping.
In any case the window should be resized only once when the cursor changes zone. If it is not the case then something should be fixed.

**Comment by onguarde** [comment] 2022-07-22 09:26
[AltSnap.ini.txt](https://github.com/RamonUnch/AltSnap/files/9166471/AltSnap.ini.txt)

**Comment by onguarde** [comment] 2022-07-22 09:53
The tearing issue is a lot less, it's barely noticeable but it's there. Video recording makes it worse, so it's difficult to show exactly. 

https://user-images.githubusercontent.com/681355/180410543-967f7f10-f794-465c-9b42-48850d527e93.mp4

Notice in the video, the monitor is split into 3. Dragging one window from the left all the way to right, is not a very nice visual experience. It snaps to each layout position en-route to it's final destination.


I've tried to play with this setting, but didn't notice any difference. 
> AutoSnap=0
> ;AutoSnap=2; orig
> ; Makes a window automatically snap to other windows, without the need to press shift.
> ; List of settings:
> ; 0: Disabled.
> ; 1: Automatically snaps to the screen borders and the taskbar.
> ; 2: Also automatically snaps to the outside of windows.
> ; 3: Also automatically snaps to the inside of windows.

**Comment by Ichisich** [comment] 2022-07-22 10:11
OK, I think I have it.

I can reproduce a resize flicker as soon as I initiate a zone snap. It's even noticeable without changing the zone.
Try it with this setting enabled/disable:
![Screenshot 2022-07-22 120859](https://user-images.githubusercontent.com/31080003/180417636-e76eb57d-58c7-4bab-8dbc-727cd69e5608.png)

**Comment by onguarde** [comment] 2022-07-22 10:15
i tried but I can't tell any difference. Mine is on disabled.

**Comment by Ichisich** [comment] 2022-07-22 10:24
From your videos, which would be more useful with a higher frame rate, it looks like your PC struggles with resizing the window fast enough to be unnoticeable.
This is why `FullWindow=0` bypasses this issue.

You could experiment with different resizes rates.

**Comment by RamonUnch** [comment] 2022-07-22 12:38
AutoSnap setting will not change anything, I agree with Ichisich, your problem is just a slow desktop, there is no much I can do outside of FullWin=0.
The initial flicker should no longer be there with the 1.54 test 10 and later...
With test11, you can have a transparent window that may fix your problem.

**Comment by RamonUnch** [comment] 2022-07-22 12:47
A thing that might help is the Max Aero Speed;
I will implement it for Zone snapping, for now it is not implemented.

**Comment by RamonUnch** [comment] 2022-07-22 13:09
Here we go:
With the below build the windows will be not moved if the cursor speed is higher than the Max snapping (see Advanced tab).

[AltSnap1.54test12_x64.zip](https://github.com/RamonUnch/AltSnap/files/9167935/AltSnap1.54test12_x64.zip)

I suggest you start with a Max Snapping Speed of 64pixels/64ms, then try increasing or decreasing depending on your taste.

If the cursor goes faster than the max snapping speed, then the windows will not be moved until the cursor slows down. like this you can move quickly your cursor over a zone without having the window snap to it.

**Comment by RamonUnch** [comment] 2022-07-22 13:35
Note that the above test build also contains the transparent rectangle option available via the `TransWinOpacity=128` in the `[Performance]` section of the .ini file

**Closed** 2022-07-23 20:44 UTC
Labels: bug

**Comment by onguarde** [comment] 2022-07-24 09:27
awesome, this works perfectly too, i put my value as 16. 

![image](https://user-images.githubusercontent.com/681355/180640538-c2813d65-cd0a-4b4f-aa6e-01f4b07f5ecf.png)

However, I ended up preferring FullWin=0, "transparent rectangle" option.
https://github.com/RamonUnch/AltSnap/issues/223

This one is perfectly usable really, just a matter of preference. 

Because this relies on the speed of the cursor, it's harder to control. However, the advantage is you can quickly try multiple snap layouts, without releasing your left mouse drag.

**Comment by onguarde** [comment] 2022-07-24 09:51
![image](https://user-images.githubusercontent.com/681355/180641533-2177bd07-35cf-413c-bef3-70c0271a56ab.png)

In the advanced settings option, i don't get what is the number 32 in the second box. I can't edit this from GUI. Looking at the Altsnap.ini, it seems to be linked to AeroSpeedTau=32.

What does that do? 

> Max Snapping Speed of 64pixels/**64ms**,

I presume it corresponds to the second value in your quote above? So in my case, 

> AeroMaxSpeed=16
> AeroSpeedTau=32

max speed =16pixels/32ms.
need to move 16 pixels in 32 ms.
