### ISSUE TITLE
Lag when dragging and resizing Alacritty

### ISSUE THREAD

**Issue by brian6932** [RamonUnch/AltSnap#160] opened 2022-02-08 01:32 UTC
So to preface, I've personally had this issue for a few yrs now, and it's pretty annoying, however, today I asked a friend who also uses both programs, and he also reported the same issue.
I have not experienced this kind of lag when using AltSnap with any other program except Alacritty, so there's probably something weird with their implementation of GPU acceleration.

Drag:
https://z.zz.fo/sdxFH.gif

Resize:
https://z.zz.fo/FZEMS.gif

I'll likely crosspost this issue on their repo later too.

EDIT: I fixed the files, for some reason my ffmpeg settings were exporting the gifs wrong

**Comment by RamonUnch** [comment] 2022-02-08 07:44
You do you have any lagging when resizing natively with window?
A solution would be to use the [latest AltSnap ](https://github.com/RamonUnch/AltSnap/issues/158#issuecomment-1031312893)test build and and force FullWin=0 in the [Performance] section of the .ini file
Of course you would only see a hollow window when dragging.

**Comment by Ichisich** [comment] 2022-02-08 12:16
It's hard to depict lag with 25fps gifs.
So I tested it with **Alacritty portable** myself and here are some 60fps videos:

My preferred settings:
`RefreshRate=0`
`MoveRate=1`
`ResizeRate=2`


https://user-images.githubusercontent.com/31080003/152981000-64417140-0456-4d1d-812e-a20096dfa0ed.mp4



https://user-images.githubusercontent.com/31080003/152981023-8dade67c-f12e-4a82-a4fb-ce22bccf9f48.mp4



https://user-images.githubusercontent.com/31080003/152981046-e70f39bf-32f3-487b-92fc-2a9e2710294f.mp4



https://user-images.githubusercontent.com/31080003/152981060-8d5950c7-8a0e-42fd-8381-e47236af45cc.mp4


Nothing unusual. 
Dragging behaves like every other ordinary application and resizing is laggier compared to, for example, Powershell but not limited to AltSnap.

https://user-images.githubusercontent.com/31080003/152982204-072785ba-a83c-4f0a-bfca-5357778005aa.mp4


AltSnap does have some problems/quirks when it comes to resizing and dragging windows that contain animations, though.
Most likely in game engines.

https://user-images.githubusercontent.com/31080003/152984099-34dd0cae-0565-48da-b19b-3e3c82ea13d1.mp4

Windows nativ dragging/resizing stops drawing as long as I don't release left-click. 
AltSnap, in contrast, refreshes the content without any limitation, which can has its benefits, too.

**Comment by brian6932** [comment] 2022-02-08 12:41
@Ichisich The gifs I sent are both 60 fps lol

**Comment by brian6932** [comment] 2022-02-08 12:47
> Do you have any lagging when resizing natively with window?

@RamonUnch No, just on Alacritty nothing else, it seems to be more pronounced when it is in foreground as well, I'll try 1.5.0 too though.

**Comment by Ichisich** [comment] 2022-02-08 12:48
> @Ichisich The gifs I sent are both 60 fps lol

The source material was probably in 60fps, but the gifs  are converted to 25fps:

![mpv-shot0001](https://user-images.githubusercontent.com/31080003/152989846-35706340-7040-4045-ac45-302af349b818.png)

**Comment by brian6932** [comment] 2022-02-08 12:50
@Ichisich No lol, those gifs have 16ms in between each frame, that is 60fps

**Comment by brian6932** [comment] 2022-02-08 12:57
@Ichisich After downloading from image host, it seems like the image host may have re-encoded it, I'll try a different one.

**Comment by brian6932** [comment] 2022-02-09 00:57
> Also you may experience less lag if you use higher values for `MoveRate and ResizeRate`

@RamonUnch Changing both of these values to >= 3 fixed it. Would it be possible to hardcode Alacritty to have a `MoveRate` and `ResizeRate` of 3? I like how those values feel on 1 globally, and my only issue I've ever encountered regarding those values is with Alacritty.
Since this was reproducible, I think this may be a good option if possible.

**Comment by RamonUnch** [comment] 2022-02-09 08:14
I do not want to code per-app resizing framerate, there is already far too much special cases hard coded, I would rather find a better way to resize than add a list of programs that will never end.
I personally do know a few programs that are *slow* to resize I just use in general `RefreshRate=16` it makes window moving slightly less smooth but it also reduces CPU usage a lot and avoids some trails when moving any window, it also reduces window distortion when resizing from the top-left.
The *strange* thing with Alacritty is that usually it is never slow to move a window, because the program does not have to do any re-drawing (The OS takes care of copying its content).

**Comment by Ichisich** [comment] 2022-02-09 10:57
> Also, I fixed the recordings, so shouldn't be as low frame rate now.

It seems dragging is fine as long as Alacritty is not focused.
As a workaround, you could bind `Lower window` to a key/wheel  and leave `Focus window when dragging` unchecked.
So you could keep Move/Resizerate globally at 1.


> The _strange_ thing with Alacritty is that usually it is never slow to move a window, because the program does not have to do 
any re-drawing (The OS takes care of copying its content).

This seems to be the case only with 2D applications, which are handled by the GDI.
3D accelerated content, as shown with the Duke_Nukem_Raze video, still gets redrawn constantly, even while simply dragging.

I don't know what Windows nowadays uses, but I doubt It's still `SetWindowPos()` and its `SWP_NOREDRAW` flag.

**Comment by RamonUnch** [comment] 2022-02-09 11:11
Probably with GL applications you are right, but even if your program in GDI prevent some `BitBlt` there is still an additional kind of `BitBlt` performed by DWM.exe. it is a huge mess and it makes life even more complicated for people wanting to develop programs with smooth resizing.

The most exhaustive info I found on the topic talks about both GDI and DWM.exe:
https://stackoverflow.com/questions/53000291/how-to-smooth-ugly-jitter-flicker-jumping-when-resizing-windows-especially-drag
On older windows you just had to understand about `WM_NCCALCSIZE` and implement it yourself *properly* and everything was PERFECT. Now with DWM.exe there is an additional layer of complexity.

**Comment by brian6932** [comment] 2022-02-09 18:42
> It seems dragging is fine as long as Alacritty is not focused.

@Ichisich It's less bad, however, the same issues do happen while unfocused. Just appears that way cause the recording is not super long.

**Comment by RamonUnch** [comment] 2022-02-11 11:09
@brian6932 
I am working on an alternative refresh rate, try this version of hooks.dll
The idea is that, before moving the window, AltSnap waits for the event time stamp to be different from the previous one.
I am not sure it will improve anything but to try it you need to set: `RezTimer=1` in the `[Performance]` section of the .ini file, and be sure that yu set `RefreshRate=0`, when you enable RezTimer, then the MoveRate and ResizeRate options are ignored.

```
RezTimer=1
; Set to 1 to move the window only when the timestamp of
; a mouse event is different from the previous one.
; MoveRate and ResizeRate will have no effect if RezTimer=1
; I also advise to set RefreshRate=0, if you use this option.
```

64 bit build: [hooks_1.50test13_x64.zip](https://github.com/RamonUnch/AltSnap/files/8048073/hooks_1.50test13_x64.zip)
32 bit build: [hooks_1.50test13_i386.zip](https://github.com/RamonUnch/AltSnap/files/8048079/hooks_1.50test13_i386.zip)

**Comment by brian6932** [comment] 2022-02-11 12:14
@RamonUnch `RezTimer=1` fixes the issue, however, it doesn't feel very smooth, and makes movement of windows in general feel very jagged/janky

**Comment by RamonUnch** [comment] 2022-02-11 12:34
It is normal, that's because the resolution of the Windows event timer is around 16ms, so altsnps only moves the window every 16ms which is a bit insuficient for smoothness.

**Comment by Ichisich** [comment] 2022-02-11 12:42
Is the window event timer hardcoded or dependent on the monitor refresh rate?

As far as I can tell, the difference is negligible in regular applications.
In some worst case (opengl/vulkan) accelerated applications dragging feels slightly worse with `RezTimer=1` than with `MoveRate=1`.
Resizing on the other hand can profit of `RezTimer=1` compared to `ResizeRate=2`.

**Comment by RamonUnch** [comment] 2022-02-11 12:42
I was not sure on how bad it would be, could you compare `RezTimer=1`+`RefreshRate=0` vs `RezTimer=0`+`RefreshRate=1` ?

**Comment by Ichisich** [comment] 2022-02-11 12:50
The decline in reactivity is identical.

**Comment by brian6932** [comment] 2022-02-11 13:15
For me the responsiveness is very very different, I am at 1440p 165Hz, very far from negligable

**Comment by RamonUnch** [comment] 2022-02-11 13:54
the timer accuracy depends on windows version, on win9x it was 1ms, on NT it depends on the functions and is typically around 50ms or 16ms.
I should be able to increase the accuracy of the Sleep() function using the timeBegin/endPeriod in the WINMM api, it should not be hard.

**Comment by RamonUnch** [comment] 2022-02-11 14:10
[hooks_1.50test14_i386.zip](https://github.com/RamonUnch/AltSnap/files/8049161/hooks_1.50test14_i386.zip)
[hooks_1.50test14_x64.zip](https://github.com/RamonUnch/AltSnap/files/8049169/hooks_1.50test14_x64.zip)

This one uses an *Accurate Sleep* function (in theory),
try with `RezTimer=0`+`RefreshRate=small values`
And tell me if you see any improvement.

**Comment by RamonUnch** [comment] 2022-02-11 14:13
In theory I should have a precision of a couple miliseconds with this function (used in the above builds):
```
static void ASleep(DWORD duration_ms)
{   // This absurd code makes Sleep() more accurate
	// - without it, Sleep() is not even +-10ms accurate
	// - with it, Sleep is around +-1.5 ms accurate
	TIMECAPS tc;
	timeGetDevCaps(&tc, sizeof(tc));
	timeBeginPeriod(tc.wPeriodMin); // begin accurate Sleep() !

	Sleep(duration_ms); // perform The SLEEP

	timeEndPeriod(tc.wPeriodMin);
}
```

**Comment by RamonUnch** [comment] 2022-02-11 14:18
Also I have a 60Hz monitor, so for me seeing anything is quite hard, all seems fine to me.

**Comment by RamonUnch** [comment] 2022-02-11 14:23
@brian6932 I guess for you `RezTimer=0`+`RefreshRate=3-to-5` should be fine for you (165Hz=>6ms meriod)

**Comment by Ichisich** [comment] 2022-02-11 15:28
1.50Test14 definitely resizes smoother than 1.49.

https://user-images.githubusercontent.com/31080003/153619545-4419d053-e829-4aad-8238-df9cbeb8d2bf.mp4

https://user-images.githubusercontent.com/31080003/153619564-63aea5c6-6f1a-4f52-8923-e1a18c932694.mp4

https://user-images.githubusercontent.com/31080003/153619576-28d93beb-3e12-40f0-8b63-83fc100cee14.mp4

**Comment by RamonUnch** [comment] 2022-02-11 16:08
Well we look crazy resizing windows back and forth like nuts.
This accurate sleep will be in the next release.
Coming soon hopefully.

**Comment by Ichisich** [comment] 2022-02-11 17:50
The irony is, I don't even use resizing and dragging in most cases.
Just zap it into its zone or empty space.

**Comment by RamonUnch** [comment] 2022-02-11 18:01
btw this hooks.dll has a new action: `SideSnap` (Snap to side/corner)
You can set it via the .ini file. GUI comming soon...

**Comment by brian6932** [comment] 2022-02-11 20:44
@RamonUnch I forgot to mention, swapping the hooks.dll file with no settings changes did mostly fix lag on resize for Alacritty, so at least half of this is fixed, just `MoveRate<=2` is all that's causing issues now

**Comment by brian6932** [comment] 2022-02-13 03:23
@RamonUnch Minor thing, I'm not entirely sure if this is with the updated handlers or 1.5.0, I am leaning more towards handlers, but sometimes when I release my LMB and Alt is already released, it still keeps the drag state of the window, a double click resolves it though.

**Comment by RamonUnch** [comment] 2022-02-13 08:02
It is a dev build indeed, give me your .ini file (you can zip it then attach it in a post).
Also Try with the latest dev build:
[AltSnap1.50bin.zip](https://github.com/RamonUnch/AltSnap/files/8055159/AltSnap1.50bin.zip)
[AltSnap1.50test17bin_x64.zip](https://github.com/RamonUnch/AltSnap/files/8055160/AltSnap1.50test17bin_x64.zip)

If you find a sequence that can reproduce it it would help.

**Comment by brian6932** [comment] 2022-02-13 11:37
@RamonUnch np, this is my ini: [AltSnap.zip](https://github.com/RamonUnch/AltSnap/files/8055434/AltSnap.zip)
I'll lyk if it re-occurs

**Comment by RamonUnch** [comment] 2022-02-13 13:24
Well, I think I found a way to reproduce by snapping an unresponsive window to a corner and moving the cursor while it is resizing, releasing all keys. Sometime the move does not stop. I will try to see how to fix it.

**Comment by RamonUnch** [comment] 2022-02-13 14:23
this one fixes the one I described: [hooks1.50test18_x64.zip](https://github.com/RamonUnch/AltSnap/files/8055712/hooks1.50test18_x64.zip)

**Comment by RamonUnch** [comment] 2022-02-13 18:25
Ok try with this one (should not be fixed) and when it happens, just press the ESC key (it should fix it) and show me the content of the `ad.log` file that will be created.
It will help me debug things out.

some Informations on the internal state of AltSnap are logged on ESC with this version

[hooks1.50test19ESC_LOG_x64.zip](https://github.com/RamonUnch/AltSnap/files/8056332/hooks1.50test19ESC_LOG_x64.zip)

Also are-you sure it did not happen in 1.49 before?

**Comment by brian6932** [comment] 2022-02-13 19:42
> Also are-you sure it did not happen in 1.49 before?

I don't believe so

**Comment by RamonUnch** [comment] 2022-02-13 19:45
> I don't believe so

That is good it means it can be fixed without much trouble. Regression probably appeared when I generalized the way actions are handled.

**Comment by RamonUnch** [comment] 2022-02-14 07:53
Also maybe you used `ResizeRate=2` with the old version? because you are using 1 at this day.
Not sure if it may change something. but I am really unable to reproduce it myself. I will be waiting for the log fiile.

**Comment by brian6932** [comment] 2022-02-14 10:07
@RamonUnch I managed to get it again
[ad.log](https://github.com/RamonUnch/AltSnap/files/8059782/ad.log)

**Comment by RamonUnch** [comment] 2022-02-14 10:15
Thanks, I will check this out.

**Comment by RamonUnch** [comment] 2022-02-14 10:25
Well, in both cases i got:
```
action=1
moving=1
ctrl=0
shift=0
alt=0
alt1=0
clickbutton=2
hwnd=4b6065e
lwhwnd=0
lwend=2
blockaltup=0
blockmouseup=0
ignorekey=0

```
I was hoping that I would see an inconsistent state, but is is exactly what one should see when dragging the window (without touching the keybard anymonr). It seems that AltSnap did not register the mouse up event. does it happen on every programs with you?

**Comment by brian6932** [comment] 2022-02-14 21:15
I think I have had it happen on 2 programs, I'll try to trigger it again though

**Comment by RamonUnch** [comment] 2022-02-15 08:10
From the tests I have performed, it seems that if the mouse hook thread is being busy for a while, then it does not get all mouse events, so in some sides cases, when treating some events take a while, it does not register all mouse events.
Because of this AltSnap can be in inconsistent state.
The fix would be to be sure that the mouse thread is always super fast, however there are some cases where I still do have to loose time. Maybe some stuff are being slightly slower than with 1.49 and it happens more. Also, maybe the different handling of resize rate changed something.

Here again is a small revision of the hooks.dll that *might* fix it (unlikely though). but it does fixes some bug when snapping.
[hooks1.50test20_x64.zip](https://github.com/RamonUnch/AltSnap/files/8067033/hooks1.50test20_x64.zip)

**Comment by RamonUnch** [comment] 2022-02-15 08:20
Note maybe increasing MoveRate and ResizeRate a little might reduce the problem, because the mouse thread will pile up less events. or maybe setting a small value for RefreshRate (which behaves now).

**Comment by brian6932** [comment] 2022-02-15 09:34
Ok it occurred again, but I think it's occurring less now

**Comment by RamonUnch** [comment] 2022-02-16 13:20
Maybe it is related to the Hotclicks, try disabling them.

**Comment by RamonUnch** [comment] 2022-02-16 17:46
I can get the bug by snapping a window to the top and releasing alt then the mouse while the maximization did not finish, but it happened also with 1.49 and I do not see how to fix it for now.

**Comment by brian6932** [comment] 2022-02-16 17:55
I don't think I experienced this issue before 1.5.0 🤷 It's possible that it existed in older builds, but never triggered for me and was made worse somehow, I really don't remember an issue like this before 1.5.0.

**Comment by RamonUnch** [comment] 2022-02-16 18:00
I thrust you but I also think that I am unable to reproduce the specific reason that on your machine you are getting this grabbing.
More digging is required.
How often does it happen? how disturbing is it?

**Comment by brian6932** [comment] 2022-02-16 19:53
Interval is not super consistent, but about 1-4 times an hour, depending if I'm using AltSnap heavily or not

**Comment by RamonUnch** [comment] 2022-02-16 21:55
Well maybe you could try the test8 build that did not include yet the generalization of the title bar actions: https://github.com/RamonUnch/AltSnap/issues/110
Your .ini You can set `LowerWithMMB=3` in the [input] section of the ini file to simulate the title bar action that you are using, otherwise your .in file should work.
If it does or does not happen, then I will have less code to review

**Comment by brian6932** [comment] 2022-02-16 22:51
@RamonUnch ok, so after really trying hard to trigger it, I managed to reproduce the bug a few times in test8, however, it is much more difficult to reproduce in this version

**Comment by RamonUnch** [comment] 2022-02-17 07:33
> It seems to occur near my monitor's boundaries I think

You mean when snapping? i guess.
Maybe an other test would be to try for a couple hours with the latest test build but disabling title bar actions.

**Comment by brian6932** [comment] 2022-02-17 09:23
Not quite snapping, just near borders, that was more or less the way I could trigger it on test8, it may have just been the angle I was going at, but the newer builds is way easier to trigger, and trigger anywhere


> Maybe an other test would be to try for a couple hours with the latest test build but disabling title bar actions.

I'll try this regardless

**Comment by brian6932** [comment] 2022-02-17 09:30
Still triggers

**Comment by RamonUnch** [comment] 2022-02-17 10:06
Very good info.
I made an even more loggy version of the hooks.dll
It will save the mouse button UP/DOWN events and the ALT UP/DOWN events as well as show the state on ESC.
When it happens again, press esc and then send me the log file:
by snapping I was able to have this one:
```
ALT DOWN, LastError=0
button=2, DOWN, LastError=0
ALT UP, LastError=0
IgnoreKey, LastError=0
IgnoreKey, LastError=0
ESCAPE KEY WAS PRESSED:
action=1
moving=1
ctrl=0
shift=0
alt=0
alt1=0
clickbutton=2
hwnd=19200d6
lwhwnd=0
lwend=0
lwmaximize=0
lwmoveonly=1
lwsnap=0
blockaltup=0
blockmouseup=0
ignorekey=0
```
You see that before the ESCAPE KEY there is now button up event, and this happens because the window was very unresponsive when maximizing it (SeaMonkey web browser with a heavy page). This was the same with 1.49. What we want to see is if we can figure out the difference with the more common events that are occurring to you.
[hooks1.50test21_LOG_x64.zip](https://github.com/RamonUnch/AltSnap/files/8087638/hooks1.50test21_LOG_x64.zip)

**Comment by Ichisich** [comment] 2022-02-17 12:03
I can reproduce it reliably with `ResizeUp=SideSnap` and then dragging or resizing.
Could be an entirely different issue which happen to trigger the same consequence, but here is the log regardless.
AltSnaptTest17 with test21_LOG_hook:
[ad.zip](https://github.com/RamonUnch/AltSnap/files/8088444/ad.zip)

**Comment by RamonUnch** [comment] 2022-02-17 12:34
Well this one was easy, I was just blocking the mouse up event when I should not. but it is just related to the SideSnap action.
From your .log file it seems that you pressed ESC before releasing the Alt key at some point. is that the case? or are the input actually wrong? I am still reviewing it.
[hooks1.50test22_LOG_x64.zip](https://github.com/RamonUnch/AltSnap/files/8088632/hooks1.50test22_LOG_x64.zip)

**Comment by Ichisich** [comment] 2022-02-17 12:45
> From your .log file it seems that you pressed ESC before releasing the Alt key at some point. is that the case?

win+rightclick(resizeup=sidesnap)->win+leftclick(dragging)->ESC(while the window is still draggable without win or leftclick)
win is kept pressed in-between resizeup and leftclick, but released before pressing ESC.
[ad.zip](https://github.com/RamonUnch/AltSnap/files/8088682/ad.zip)

BTW: hooktest22 fixes the issue

**Comment by RamonUnch** [comment] 2022-02-18 14:21
Normally if you do not use them as hotkeys altSnap should not lock anything, be sure that hotclick is set to an empty value in the ini file. `Hotclicks=`
There is no consistent way to have XButtons mapped as hotclick unless I completely block it, like it is stated in the description of the hotclicks. maybe I will find a better way.

**Comment by brian6932** [comment] 2022-02-18 14:41
Btw, I have been unable to trigger the held drag/resize state bug in test22, so it seems like it's fixed, hopefully this is not jinxing it lol

**Comment by brian6932** [comment] 2022-02-18 18:40
@RamonUnch Uhh lol, that's good and all, this thread got kinda of sidetracked since we didn't open new issues. But the issue on Alacritty drag still exists, so I don't think this issue should be closed. The resizing lag is gone, just dragging now.

**Comment by RamonUnch** [comment] 2022-02-18 18:51
You are right indeed...

**Comment by RamonUnch** [comment] 2022-02-23 21:17
Ok, I im still "guessing", it seems that for the Resize it is fixed by not using the `SWP_ASYNCWINDOWPOS` flag, in 1.51, I still use it for movement, because otherwise some windows get drawn badly, however those windows never have resizing borders (I think). So here is a version that does not uses `SWP_ASYNCWINDOWPOS` flag when moving a window that has some sizing borders.
The reason is that in order to wait for the end of painting I used to send a `WM_SYNCPAINT` message but it seems some programs refuse to interpret it and return instantly instead.
Tell me if it works for you:
[hooks1.52test1_x64.zip](https://github.com/RamonUnch/AltSnap/files/8127839/hooks1.52test1_x64.zip)

**Comment by brian6932** [comment] 2022-02-23 23:35
@RamonUnch Yes this worked, it is quite an impressive difference lol

**Closed** 2022-02-24 08:20 UTC
Labels: bug, WIP
